image: sunbr0/gb_img:a23de906

stages:
    - build

rom:
    stage: build
    script:
        - git submodule update --init
        - make lib
        - make check
        - make
    artifacts:
        paths:
            - build/game.gb
